#!/bin/sh

### BEGIN INIT INFO
# Provides:          phantap-antileak
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PhanTap Anti-leak init script
# Description:       This script installs anti-leak rules for PhanTap
### END INIT INFO

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_start()
{
    log_daemon_msg "Installing PhanTap anti-leak rules"
    /etc/init.d/phantap block_net
    log_daemon_msg "PhanTap anti-leak rules installed"
    log_end_msg $?
}

case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        do_start
        ;;
    *)
        echo "Usage: $0 {start|restart|reload|force-reload}"
        exit 1
        ;;
esac

exit 0
